In [50]:
# Q1) Gradiend descent
import numpy as np
import pandas as pd

In [51]:
df=pd.read_csv("FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding="latin-1")

In [52]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [53]:
df['Area'].unique()

array(['Algeria', 'Angola', 'Benin', 'Botswana', 'Burkina Faso',
       'Cabo Verde', 'Cameroon', 'Central African Republic', 'Chad',
       'Comoros', 'Congo', "Côte d'Ivoire", 'Djibouti', 'Egypt',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR', 'Gabon', 'Gambia', 'Ghana',
       'Guinea', 'Guinea-Bissau', 'Kenya', 'Lesotho', 'Liberia',
       'Madagascar', 'Malawi', 'Mali', 'Mauritania', 'Mauritius',
       'Morocco', 'Mozambique', 'Namibia', 'Niger', 'Nigeria', 'Rwanda',
       'Sao Tome and Principe', 'Senegal', 'Seychelles', 'Sierra Leone',
       'South Africa', 'Sudan', 'Sudan (former)', 'Togo', 'Tunisia',
       'Uganda', 'United Republic of Tanzania', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [54]:
len(df['Area'].unique())

49

In [55]:
df_grouped = df.groupby('Area')['Y2017'].sum()

In [56]:
df_grouped

Area
Algeria                         325644.27
Angola                          229159.57
Benin                           124771.22
Botswana                         22101.30
Burkina Faso                    101855.07
Cabo Verde                       14650.74
Cameroon                        232030.43
Central African Republic         29937.00
Chad                             71594.68
Comoros                             59.84
Congo                            41181.68
Côte d'Ivoire                   224599.01
Djibouti                         22729.91
Egypt                           866379.92
Eswatini                         54343.33
Ethiopia                        448683.76
Ethiopia PDR                         0.00
Gabon                            27979.64
Gambia                           23154.18
Ghana                           337599.06
Guinea                           98138.87
Guinea-Bissau                    19102.77
Kenya                           264660.66
Lesotho                          21267.96
Liberia                          29342.20
Madagascar                      131197.73
Malawi                          181098.71
Mali                            149928.33
Mauritania                      156665.46
Mauritius                        51114.83
Morocco                         388495.36
Mozambique                      161407.98
Namibia                          29874.89
Niger                           126707.58
Nigeria                        1483268.23
Rwanda                           73663.69
Sao Tome and Principe            12662.63
Senegal                          95681.15
Seychelles                         442.34
Sierra Leone                     55311.33
South Africa                    517590.54
Sudan                           239931.92
Sudan (former)                       0.00
Togo                             49841.88
Tunisia                         124167.20
Uganda                          213950.38
United Republic of Tanzania     322616.85
Zambia                          103223.77
Zimbabwe                         75919.34
Name: Y2017, dtype: float64

In [57]:
df_grouped = df_grouped.sort_values()

# Assuming you want the 7th lowest value (index position 6), get the value
seventh_lowest_sum = df_grouped.iloc[6]

In [58]:
seventh_lowest_sum

19102.77

In [61]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [62]:
df['Item Code'].unique()

array([2501, 2901, 2903, 2941, 2905, 2511, 2805, 2513, 2514, 2515, 2516,
       2517, 2518, 2520, 2907, 2532, 2531, 2533, 2535, 2534, 2908, 2536,
       2537, 2909, 2542, 2543, 2745, 2911, 2546, 2547, 2549, 2912, 2551,
       2913, 2555, 2556, 2557, 2558, 2559, 2560, 2561, 2563, 2570, 2914,
       2571, 2572, 2573, 2574, 2575, 2576, 2577, 2578, 2579, 2580, 2582,
       2586, 2918, 2601, 2602, 2605, 2919, 2611, 2612, 2613, 2614, 2615,
       2616, 2617, 2618, 2619, 2620, 2625, 2922, 2630, 2633, 2635, 2923,
       2640, 2641, 2642, 2645, 2924, 2655, 2656, 2657, 2658, 2659, 2943,
       2731, 2732, 2733, 2734, 2735, 2945, 2736, 2946, 2740, 2743, 2737,
       2781, 2782, 2949, 2744, 2948, 2848, 2960, 2761, 2762, 2763, 2764,
       2765, 2766, 2767, 2961, 2769, 2775, 2928, 2680, 2899, 2541, 2562,
       2581])

In [63]:
df[df['Area Code']==2015]

Empty DataFrame
Columns: [Area Code, Area, Item Code, Item, Element Code, Element, Unit, Y2014, Y2015, Y2016, Y2017, Y2018]
Index: []

In [75]:
df_filtered = df[(df['Area'] == 'Madagascar')]
df_filtered['']

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
30715,129,Madagascar,2501,Population,511,Total Population - Both sexes,1000 persons,23590.00,24234.00,24894.00,25571.00,26262.00
30716,129,Madagascar,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
30717,129,Madagascar,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,1986.00,1922.00,1918.00,1943.00,1938.00
30718,129,Madagascar,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,44.45,43.26,43.35,43.94,44.17
30719,129,Madagascar,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,22.18,22.97,23.83,25.26,24.12
...,...,...,...,...,...,...,...,...,...,...,...,...
32149,129,Madagascar,2899,Miscellaneous,5142,Food,1000 tonnes,10.00,11.00,11.00,11.00,12.00
32150,129,Madagascar,2899,Miscellaneous,645,Food supply quantity (kg/capita/yr),kg,0.44,0.44,0.44,0.44,0.44
32151,129,Madagascar,2899,Miscellaneous,664,Food supply (kcal/capita/day),kcal/capita/day,0.00,0.00,0.00,0.00,0.00
32152,129,Madagascar,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01
32153,129,Madagascar,2899,Miscellaneous,684,Fat supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01

In [64]:
grouped = df[['Y2017', 'Area']].groupby('Area').sum()

# Find the area with the highest sum in 2017
area_highest_sum = grouped.idxmax()[0]

print("Area with the highest sum in 2017:", area_highest_sum)

Area with the highest sum in 2017: Nigeria

In [66]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [67]:
missing_count = df['Y2014'].isnull().sum()

# Calculate the total number of entries in the column
total_entries = len(df['Y2014'])

# Calculate the percentage of missing data
percentage_missing = (missing_count / total_entries) * 100

# Round the percentage to 3 decimal places
percentage_missing = round(percentage_missing, 3)

print("Total number of missing data in column Y2014:", missing_count)
print("Percentage of missing data in column Y2014:", percentage_missing, "%")

Total number of missing data in column Y2014: 1589
Percentage of missing data in column Y2014: 2.607 %

In [70]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [69]:
madagascar_protein_2015 = df[df['Area'] == 'Madagascar']['Y2015']

# Calculate the total protein supply quantity in Madagascar for 2015
total_protein_2015 = madagascar_protein_2015.sum()

print("Total protein supply quantity in Madagascar in 2015:", total_protein_2015)

Total protein supply quantity in Madagascar in 2015: 1429

In [74]:
subset_df = df[['Y2017', 'Area']]

grouped = subset_df.groupby('Area')['Y2017'].sum().reset_index()

sorted_grouped = grouped.sort_values(by='Y2017')

seventh_lowest_area = sorted_grouped.iloc[6]['Area']

print(seventh_lowest_area)

Guinea-Bissau